#It is recommended to set your bot permission to only "send messages".
#The plugin only requires the bot to have access to send messages in channels it is seeing.
#DO NOT SHARE YOUR TOKEN ANYONE!
token: "YOUR-BOT-TOKEN"
#Options: "ONLINE" , "DO_NOT_DISTURB" , "IDLE" , "INVISIBLE".
bot-status: "ONLINE"
#If the activity status is above 15 letters, it will instead use "Towny". Spaces count too.
activity: "Peti's Plugin"
